export const SOMETHING_REQUEST = 'SOMETHING_REQUEST';
export const SOMETHING_FAILURE = 'SOMETHING_FAILURE';
export const CHANGE_LOCALE = 'CHANGE_LOCALE';
export const NOTIFICATION_STATUS = 'NOTIFICATION_STATUS';
// filter services
export const SET_SERVICE_FILTERS = 'SET_SERVICE_FILTERS';
// reset error
export const RESET_ERROR_SUCCESS = 'RESET_ERROR_SUCCESS';
// set error
export const SET_ERROR_SUCCESS = 'SET_ERROR_SUCCESS';
// retrieve password
export const RETRIEVE_PASSWORD_REQUEST = 'RETRIEVE_PASSWORD_REQUEST';
export const RETRIEVE_PASSWORD_SUCCESS = 'RETRIEVE_PASSWORD_SUCCESS';
export const RETRIEVE_PASSWORD_FAILURE = 'RETRIEVE_PASSWORD_FAILURE';
// forgot password
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';
// select building
export const SELECT_BUILDING_REQUEST = 'SELECT_BUILDING_REQUEST';
export const SELECT_BUILDING_SUCCESS = 'SELECT_BUILDING_SUCCESS';
export const SELECT_BUILDING_FAILURE = 'SELECT_BUILDING_FAILURE';
// get user
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';
// get user by id
export const GET_USER_BY_ID_REQUEST = 'GET_USER_BY_ID_REQUEST';
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS';
export const GET_USER_BY_ID_FAILURE = 'GET_USER_BY_ID_FAILURE';
// select user
export const SELECT_USER_SUCCESS = 'SELECT_USER';
// update user
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
// update user by id
export const UPDATE_USER_BY_ID_REQUEST = 'UPDATE_USER_BY_ID_REQUEST';
export const UPDATE_USER_BY_ID_SUCCESS = 'UPDATE_USER_BY_ID_SUCCESS';
export const UPDATE_USER_BY_ID_FAILURE = 'UPDATE_USER_BY_ID_FAILURE';
// logout
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
// fetch building
export const FETCH_BUILDING_REQUEST = 'FETCH_BUILDING_REQUEST';
export const FETCH_BUILDING_SUCCESS = 'FETCH_BUILDING_SUCCESS';
export const FETCH_BUILDING_FAILURE = 'FETCH_BUILDING_FAILURE';
//callback
export const CONFIRM_CALLBACK_REQUEST = 'CONFIRM_CALLBACK_REQUEST';
export const CONFIRM_CALLBACK_SUCCESS = 'CONFIRM_CALLBACK_SUCCESS';
export const CONFIRM_CALLBACK_FAILURE = 'CONFIRM_CALLBACK_FAILURE';
//request;
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const FACEBOOK_LOGIN_REQUEST = 'FACEBOOK_LOGIN_REQUEST';
export const LINKEDIN_LOGIN_REQUEST = 'LINKEDIN_LOGIN_REQUEST';
// register
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
// search buildings
export const SEARCH_BUILDING_REQUEST = 'SEARCH_BUILDING_REQUEST';
export const SEARCH_BUILDING_SUCCESS = 'SEARCH_BUILDING_SUCCESS';
export const SEARCH_BUILDING_FAILURE = 'SEARCH_BUILDING_FAILURE';
//verify
export const VERIFY_USER_REQUEST = 'VERIFY_USER_REQUEST';
export const VERIFY_USER_SUCCESS = 'VERIFY_USER_SUCCESS';
export const VERIFY_USER_FAILURE = 'VERIFY_USER_FAILURE';
//verify phone number
export const VERIFY_PHONE_NUMBER_REQUEST = 'VERIFY_PHONE_NUMBER_REQUEST';
export const VERIFY_PHONE_NUMBER_SUCCESS = 'VERIFY_PHONE_NUMBER_SUCCESS';
export const VERIFY_PHONE_NUMBER_FAILURE = 'VERIFY_PHONE_NUMBER_FAILURE';
//check code verify number
export const CHECK_VERIFY_NUMBER_REQUEST = 'CHECK_VERIFY_NUMBER_REQUEST';
export const CHECK_VERIFY_NUMBER_SUCCESS = 'CHECK_VERIFY_NUMBER_SUCCESS';
export const CHECK_VERIFY_NUMBER_FAILURE = 'CHECK_VERIFY_NUMBER_FAILURE';
// resolve report
export const RESOLVE_REPORT_REQUEST = 'RESOLVE_REPORT_REQUEST';
export const RESOLVE_REPORT_SUCCESS = 'RESOLVE_REPORT_SUCCESS';
export const RESOLVE_REPORT_FAILURE = 'RESOLVE_REPORT_FAILURE';
// retrieve the meeting room bookings
export const RETRIEVE_MEETING_ROOM_BOOKINGS_REQUEST = 'RETRIEVE_MEETING_ROOM_BOOKINGS_REQUEST';
export const RETRIEVE_MEETING_ROOM_BOOKINGS_SUCCESS = 'RETRIEVE_MEETING_ROOM_BOOKINGS_SUCCESS';
export const RETRIEVE_MEETING_ROOM_BOOKINGS_FAILURE = 'RETRIEVE_MEETING_ROOM_BOOKINGS_FAILURE';
// book a room
export const CREATE_MEETING_ROOM_BOOKING_REQUEST = "CREATE_MEETING_ROOM_BOOKING_REQUEST";
export const CREATE_MEETING_ROOM_BOOKING_SUCCESS = "CREATE_MEETING_ROOM_BOOKING_SUCCESS";
export const CREATE_MEETING_ROOM_BOOKING_FAILURE = "CREATE_MEETING_ROOM_BOOKING_FAILURE";
// nearby stops
export const NEARBY_STOPS_REQUEST = 'NEARBY_STOPS_REQUEST';
export const NEARBY_STOPS_SUCCESS = 'NEARBY_STOPS_SUCCESS';
export const NEARBY_STOPS_FAILURE = 'NEARBY_STOPS_FAILURE';
// list services
export const LIST_SERVICE_REQUEST = 'LIST_SERVICE_REQUEST';
export const LIST_SERVICE_SUCCESS = 'LIST_SERVICE_SUCCESS';
export const LIST_SERVICE_FAILURE = 'LIST_SERVICE_FAILURE';
// select a service
export const SELECT_SERVICE_REQUEST = 'SELECT_SERVICE_REQUEST';
export const SELECT_SERVICE_SUCCESS = 'SELECT_SERVICE_SUCCESS';
export const SELECT_SERVICE_FAILURE = 'SELECT_SERVICE_FAILURE';
// change password
export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';
// report
export const REPORTING_SUCCESS = 'REPORTING_SUCCESS';
export const REPORTING_FAILURE = 'REPORTING_FAILURE';
// create service
export const CREATE_SERVICE_REQUEST = 'CREATE_SERVICE_REQUEST';
export const CREATE_SERVICE_SUCCESS = 'CREATE_SERVICE_SUCCESS';
export const CREATE_SERVICE_FAILURE = 'CREATE_SERVICE_FAILURE';
// create buildings
export const CREATE_BUILDING_REQUEST = 'CREATE_BUILDING_REQUEST';
export const CREATE_BUILDING_SUCCESS = 'CREATE_BUILDING_SUCCESS';
export const CREATE_BUILDING_FAILURE = 'CREATE_BUILDING_FAILURE';
// edit building
export const EDIT_BUILDING_REQUEST = 'EDIT_BUILDING_REQUEST';
export const EDIT_BUILDING_SUCCESS = 'EDIT_BUILDING_SUCCESS';
export const EDIT_BUILDING_FAILURE = 'EDIT_BUILDING_FAILURE';
// suggest city
export const SUGGEST_CITY_REQUEST = 'SUGGEST_CITY_REQUEST';
export const SUGGEST_CITY_SUCCESS = 'SUGGEST_CITY_SUCCESS';
export const SUGGEST_CITY_FAILURE = 'SUGGEST_CITY_FAILURE';
// suggest country
export const SUGGEST_COUNTRY_REQUEST = 'SUGGEST_COUNTRY_REQUEST';
export const SUGGEST_COUNTRY_SUCCESS = 'SUGGEST_COUNTRY_SUCCESS';
export const SUGGEST_COUNTRY_FAILURE = 'SUGGEST_COUNTRY_FAILURE';
// close error message
export const CLOSE_NEARBYSTOPS_ERROR = 'CLOSE_NEARBYSTOPS_ERROR';
// list user
export const LIST_USER_REQUEST = 'LIST_USER_REQUEST';
export const LIST_USER_SUCCESS = 'LIST_USER_SUCCESS';
export const LIST_USER_FAILURE = 'LIST_USER_FAILURE';
// search user
export const SEARCH_USER_REQUEST = 'SEARCH_USER_REQUEST';
export const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS';
export const SEARCH_USER_FAILURE = 'SEARCH_USER_FAILURE';
// grant admin
export const GRANT_ADMIN_REQUEST = 'GRANT_ADMIN_REQUEST';
export const GRANT_ADMIN_SUCCESS = 'GRANT_ADMIN_SUCCESS';
export const GRANT_ADMIN_FAILURE = 'GRANT_ADMIN_FAILURE';
// get time table
export const GET_TIMETABLE_REQUEST = 'GET_TIMETABLE_REQUEST';
export const GET_TIMETABLE_SUCCESS = 'GET_TIMETABLE_SUCCESS';
export const GET_TIMETABLE_FAILURE = 'GET_TIMETABLE_FAILURE';
// eta for transports
export const ETA_TRANSPORTS_REQUEST = 'ETA_TRANSPORTS_REQUEST';
export const ETA_TRANSPORTS_SUCCESS = 'ETA_TRANSPORTS_SUCCESS';
export const ETA_TRANSPORTS_FAILURE = 'ETA_TRANSPORTS_FAILURE';
// get all buildings
export const GET_ALL_BUILDING_REQUEST = 'GET_ALL_BUILDING_REQUEST';
export const GET_ALL_BUILDING_SUCCESS = 'GET_ALL_BUILDING_SUCCESS';
export const GET_ALL_BUILDING_FAILURE = 'GET_ALL_BUILDING_FAILURE';
// get a service
export const GET_SERVICE_REQUEST = 'GET_SERVICE_REQUEST';
export const GET_SERVICE_SUCCESS = 'GET_SERVICE_SUCCESS';
export const GET_SERVICE_FAILURE = 'GET_SERVICE_FAILURE';
// calculate time to go home
export const CALCULATE_HOME_REQUEST = 'CALCULATE_HOME_REQUEST';
export const CALCULATE_HOME_SUCCESS = 'CALCULATE_HOME_SUCCESS';
export const CALCULATE_HOME_FAILURE = 'CALCULATE_HOME_FAILURE';
// add a service to current building
export const ADD_SERVICE_REQUEST = 'ADD_SERVICE_REQUEST';
export const ADD_SERVICE_SUCCESS = 'ADD_SERVICE_SUCCESS';
export const ADD_SERVICE_FAILURE = 'ADD_SERVICE_FAILURE';
// remove a service from current building
export const REMOVE_SERVICE_REQUEST = 'REMOVE_SERVICE_REQUEST';
export const REMOVE_SERVICE_SUCCESS = 'REMOVE_SERVICE_SUCCESS';
export const REMOVE_SERVICE_FAILURE = 'REMOVE_SERVICE_FAILURE';

// delete a service
export const DELETE_SERVICE_REQUEST = 'DELETE_SERVICE_REQUEST';
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS';
export const DELETE_SERVICE_FAILURE = 'DELETE_SERVICE_FAILURE';

// remove user
export const REMOVE_USER_REQUEST = 'REMOVE_USER_REQUEST';
export const REMOVE_USER_SUCCESS = 'REMOVE_USER_SUCCESS';
export const REMOVE_USER_FAILURE = 'REMOVE_USER_FAILURE';
// edit service
export const EDIT_SERVICE_REQUEST = 'EDIT_SERVICE_REQUEST';
export const EDIT_SERVICE_SUCCESS = 'EDIT_SERVICE_SUCCESS';
export const EDIT_SERVICE_FAILURE = 'EDIT_SERVICE_FAILURE';
// suggest address
export const SUGGEST_ADDRESS_REQUEST = 'SUGGEST_ADDRESS_REQUEST';
export const SUGGEST_ADDRESS_SUCCESS = 'SUGGEST_ADDRESS_SUCCESS';
export const SUGGEST_ADDRESS_FAILURE = 'SUGGEST_ADDRESS_FAILURE';
// update ui options
export const UPDATE_UI_OPTIONS_REQUEST = 'UPDATE_UI_OPTIONS_REQUEST';
export const UPDATE_UI_OPTIONS_SUCCESS = 'UPDATE_UI_OPTIONS_SUCCESS';
export const UPDATE_UI_OPTIONS_FAILURE = 'UPDATE_UI_OPTIONS_FAILURE';
// cancel verifying number
export const CANCEL_VERIFYING_NUMBER_REQUEST = 'CANCEL_VERIFYING_NUMBER_REQUEST';
export const CANCEL_VERIFYING_NUMBER_SUCCESS = 'CANCEL_VERIFYING_NUMBER_SUCCESS';
export const CANCEL_VERIFYING_NUMBER_FAILURE = 'CANCEL_VERIFYING_NUMBER_FAILURE';
// confirm terminate token
export const CONFIRM_TERMINATE_TOKEN_REQUEST = 'CONFIRM_TERMINATE_TOKEN_REQUEST';
export const CONFIRM_TERMINATE_TOKEN_SUCCESS = 'CONFIRM_TERMINATE_TOKEN_SUCCESS';
export const CONFIRM_TERMINATE_TOKEN_FAILURE = 'CONFIRM_TERMINATE_TOKEN_FAILURE';
// confirm change password
export const CONFIRM_PASSWORD_CHANGE_REQUEST = 'CONFIRM_PASSWORD_CHANGE_REQUEST';
export const CONFIRM_PASSWORD_CHANGE_SUCCESS = 'CONFIRM_PASSWORD_CHANGE_SUCCESS';
export const CONFIRM_PASSWORD_CHANGE_FAILURE = 'CONFIRM_PASSWORD_CHANGE_FAILURE';
// re authenticate
export const REAUTHENTICATE_REQUEST = 'REAUTHENTICATE_REQUEST';
export const REAUTHENTICATE_SUCCESS = 'REAUTHENTICATE_SUCCESS';
export const REAUTHENTICATE_FAILURE = 'REAUTHENTICATE_FAILURE';
// get all categories
export const GET_ALL_CATEGORY_REQUEST = 'GET_ALL_CATEGORY_REQUEST';
export const GET_ALL_CATEGORY_SUCCESS = 'GET_ALL_CATEGORY_SUCCESS';
export const GET_ALL_CATEGORY_FAILURE = 'GET_ALL_CATEGORY_FAILURE';
// sentry report
export const SENTRY_REPORT_REQUEST = 'SENTRY_REPORT_REQUEST';
export const SENTRY_REPORT_SUCCESS = 'SENTRY_REPORT_SUCCESS';
export const SENTRY_REPORT_FAILURE = 'SENTRY_REPORT_FAILURE';

export const REPORT_ERROR_SUCCESS = 'REPORT_ERROR_SUCCESS';
// Meeting room
export const GET_BUILDING_MEETING_ROOM_REQUEST = 'GET_BUILDING_MEETING_ROOM_REQUEST';
export const GET_BUILDING_MEETING_ROOM_SUCCESS = 'GET_BUILDING_MEETING_ROOM_SUCCESS';
export const GET_BUILDING_MEETING_ROOM_FAILURE = 'GET_BUILDING_MEETING_ROOM_FAILURE';

export const GET_MEETING_ROOM_REQUEST = 'GET_MEETING_ROOM_REQUEST';
export const GET_MEETING_ROOM_SUCCESS = 'GET_MEETING_ROOM_SUCCESS';
export const GET_MEETING_ROOM_FAILURE = 'GET_MEETING_ROOM_FAILURE';

export const EDIT_MEETING_ROOM_REQUEST = 'EDIT_MEETING_ROOM_REQUEST';
export const EDIT_MEETING_ROOM_SUCCESS = 'EDIT_MEETING_ROOM_SUCCESS';
export const EDIT_MEETING_ROOM_FAILURE = 'EDIT_MEETING_ROOM_FAILURE';

export const REMOVE_MEETING_ROOM_REQUEST = 'REMOVE_MEETING_ROOM_REQUEST';
export const REMOVE_MEETING_ROOM_SUCCESS = 'REMOVE_MEETING_ROOM_SUCCESS';
export const REMOVE_MEETING_ROOM_FAILURE = 'REMOVE_MEETING_ROOM_FAILURE';

export const CREATE_MEETING_ROOM_REQUEST = 'CREATE_MEETING_ROOM_REQUEST';
export const CREATE_MEETING_ROOM_SUCCESS = 'CREATE_MEETING_ROOM_SUCCESS';
export const CREATE_MEETING_ROOM_FAILURE = 'CREATE_MEETING_ROOM_FAILURE';

// select a meeting room
export const SELECT_MEETING_ROOM = 'SELECT_MEETING_ROOM';
export const SET_MEETING_ROOM_FILTER = 'SET_MEETING_ROOM_FILTER';
export const CLEAR_MEETING_ROOM = 'CLEAR_MEETING_ROOM';

// get building by service
export const GET_BUILDING_BY_SERVICE_REQUEST = 'GET_BUILDING_BY_SERVICE_REQUEST';
export const GET_BUILDING_BY_SERVICE_SUCCESS = 'GET_BUILDING_BY_SERVICE_SUCCESS';
export const GET_BUILDING_BY_SERVICE_FAILURE = 'GET_BUILDING_BY_SERVICE_FAILURE';

// count users in building
export const COUNT_USER_IN_BUILDING_REQUEST = 'COUNT_USER_IN_BUILDING_REQUEST';
export const COUNT_USER_IN_BUILDING_SUCCESS = 'COUNT_USER_IN_BUILDING_SUCCESS';
export const COUNT_USER_IN_BUILDING_FAILURE = 'COUNT_USER_IN_BUILDING_FAILURE';

export const DELETE_BUILDING_REQUEST = 'DELETE_BUILDING_REQUEST';
export const DELETE_BUILDING_SUCCESS = 'DELETE_BUILDING_SUCCESS';
export const DELETE_BUILDING_FAILURE = 'DELETE_BUILDING_FAILURE';

export const GET_BUILDING_BY_ID_REQUEST = 'GET_BUILDING_BY_ID_REQUEST';
export const GET_BUILDING_BY_ID_SUCCESS = 'GET_BUILDING_BY_ID_SUCCESS';
export const GET_BUILDING_BY_ID_FAILURE = 'GET_BUILDING_BY_ID_FAILURE';

export const UPDATE_SERVICE_IN_BUILDING = 'UPDATE_SERVICE_IN_BUILDING';

export const PIN_SERVICE_REQUEST = 'PIN_SERVICE_REQUEST';
export const PIN_SERVICE_SUCCESS = 'PIN_SERVICE_SUCCESS';
export const PIN_SERVICE_FAILURE = 'PIN_SERVICE_FAILURE';

export const UNPIN_SERVICE_REQUEST = 'UNPIN_SERVICE_REQUEST';
export const UNPIN_SERVICE_SUCCESS = 'UNPIN_SERVICE_SUCCESS';
export const UNPIN_SERVICE_FAILURE = 'UNPIN_SERVICE_FAILURE';

export const SET_TRANSPORT_FILTERS = 'SET_TRANSPORTS_FILTERS';
